[package]
name = "scaffold"
version = "0.1.0"
authors = ["Kim Hermansson <h4xrk1m@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0"
structopt = "0.3"

[dependencies.indexmap]
version = "1.3"
features = ["serde-1"]

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.toml]
version = "0.5"
features = ["preserve_order"]
