[package]
version = "0.1.2"
description = "Quickly add dependencies to your Rust project."
categories = ["command-line-utilities", "config", "development-tools", "text-editors"]
keywords = ["toml", "cargo", "scaffold", "productivity"]
name = "scaffold"
authors = ["Kim Hermansson <h4xrk1m@gmail.com>"]
edition = "2018"
homepage = "https://github.com/segfaultsourcery/scaffold"
documentation = "https://github.com/segfaultsourcery/scaffold"
license = "MIT"
readme = "README.md"

[dependencies]
serde_derive = "1.0"
structopt = "0.3"
shellexpand = "1.0.0"

[dependencies.indexmap]
features = ["serde-1"]
version = "1.3"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.toml]
features = ["preserve_order"]
version = "0.5"
