[package]
name = "empty-test-file"
version = "0.1.0"
authors = ["Kim Hermansson <h4xrk1m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
